#!/usr/bin/env php
<?php

/*
 * This file is part of the PPCRE.
 *
 * (c) Serghei Iakovlev <egrep@protonmail.ch>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

use Ppcre\Application;

require __DIR__ . '/vendor/autoload.php';

$app = new Application($argv);
$app->say();
