# This file is part of the PPCRE.
#
# (c) Serghei Iakovlev <egrep@protonmail.ch>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

name: build

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    branches:
      - master

jobs:
  linux:
    name: "Linux: PHP v${{ matrix.php }}"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        php:
          - '7.0'
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo ::set-output name=dir::$(composer config cache-files-dir)

      - name: Setup Composer Cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys:
            ${{ runner.os }}-composer-${{ env.cache-name }}-
            ${{ runner.os }}-composer-
            ${{ runner.os }}-

      - name: Setup Composer Token
        if: ${{ secrets.COMPOSER_TOKEN }}
        run: composer config github-oauth.github.com ${{ secrets.COMPOSER_TOKEN }}

      - name: Install Project Dependencies
        run: composer install --prefer-dist --no-interaction --no-ansi --no-progress --no-suggest

      - name: Fast Commands Test
        run: ./example Hello World

      - name: Success Reporting
        if: success()
        run: git log --format=fuller -5
